### ISSUE TITLE
双蓝牙连接是音频输出会出现问题

### ISSUE THREAD

**Issue by Mr-AlbertZhang** [noonchen/BTT_AppleWirelessHeadphone#1]
**I'm so sorry, if you can't read Chinese, I'll leave a message in English.**
hi，我有两个设备1.AirPower pro 2.BeatsX，会出现两个设备都在线的情况下，如果这种情况存在会出现切换的时候音频播放的输出不对的情况。
我认为逻辑应该是：轻点：断开2设备-连接1设备
长时间按：断开1设备-连接2设备
音频只可能通过一个蓝牙输出
我尝试了很多次1设备切换2设备没问题，2设备切换1设备会出现音频没有切换回来
以下是2切换1的设备截图：
**_这时候已经显示切换到1设备（Bar的显示），可以看到蓝牙已经连接上1设备，但是2设备蓝牙并没断开，所以默认输出的音频设备还是2，并没有切换到1设备，导致实际切换不成功_**
![iShot2020-05-06下午08 26 49](https://user-images.githubusercontent.com/59662570/81176736-26824180-8fd8-11ea-9304-af68b21e11bf.jpg)
![iShot2020-05-06下午08 23 49](https://user-images.githubusercontent.com/59662570/81176376-ab209000-8fd7-11ea-8d21-68868c71b2d9.jpg)

![iShot2020-05-06下午08 23 26](https://user-images.githubusercontent.com/59662570/81176394-afe54400-8fd7-11ea-9f92-35f3ebef1ed0.jpg)
![iShot2020-05-06下午08 23 05](https://user-images.githubusercontent.com/59662570/81176401-b1167100-8fd7-11ea-9b52-9e261688608c.jpg)

感谢这么好的预设。欢迎交流

**Comment by noonchen** [comment]
谢谢反馈，我明白问题所在了。我这个preset里面其实只用了BTT的“Toggle Bluetooth device”，并没有判断设备是否已经连接。

我会想办法看看，可能需要一点时间😂

**Comment by Mr-AlbertZhang** [comment]
看来我多虑了🤣，能用经典的emjo表情说明。。。说明中文...，期待你放大招🤩

**Comment by Mr-AlbertZhang** [comment]
> 谢谢反馈，我明白问题所在了。我这个preset里面其实只用了BTT的“Toggle Bluetooth device”，并没有判断设备是否已经连接。
> 
> 我会想办法看看，可能需要一点时间😂

看来我多虑了🤣，能用经典的emjo表情说明。。。说明中文...，期待你放大招🤩

**Comment by noonchen** [comment]
其实你的要求不难实现，用applescript objc就可以，只是连接一个会自动断开另一个可能不是其他用户想看到的情况。
如果你需要我可以临时给你单独写个...

最佳的的方案是用CoreAudio将输出设备强行切换到另一个设备，不过我也得学习怎么用😂（我并不是程序猿

**Comment by Mr-AlbertZhang** [comment]
你已经非常棒了👍，你的顾虑我想了下，也非常有道理，有些人确实需要同时连接两个蓝牙设备，Macos默认音频只能从一个通道输出吧（能不能多输出？我还没求证），大家可以继续交流，如果你有临时的版本 我可以帮你测试，zhangdong#zua.edu.cn（#换成@）再次感谢你的交流

**Comment by noonchen** [comment]
macos应该只能有一个音频输出。我现在已经找到了CoreAudio中切换设备的函数，不过调用遇到了点困难，估计还需要一些时间。

这个函数的效果就好比在system preference的sound面板中手动选择output设备，应该是符合你的预期的，我完成了会通知下你的😁

**Comment by Mr-AlbertZhang** [comment]
十分的感谢。

**Comment by Mr-AlbertZhang** [comment]
十分抱歉，再次麻烦您，现在我出现了这个问题，我找遍了所有的原因都没能解决，我实在是想不到原因了，看您遇到过这样的问题吗：您这个预设单独使用毫无问题，我想把您的预设加入我原有预设中，这样就可以封装一个新的了，我直接复制你的Bar和触发的两个设置到我的配置中，还是我按照您的配置一步操作，复制java代码-分配触发-建python脚本，但是devNAME=""内容总传不过来，所以导致找不到设备，也就显示不出来，你遇到过这样的情况吗？能给点思路吗 谢谢

**Comment by noonchen** [comment]
这是因为你复制粘贴后的预设具有不同的UUID，如果你没有改JS代码中的UUID，那么JS的代码只会更新原来那个预设的devNAME。

你需要进行的操作是：选择你复制后的预设，右键点击-选择复制UUID，然后在JS代码中把原来的那一串UUID替换掉即可～

其实BTT菜单里面有“移动trigger到”这个功能，这样就可以避免这个问题了😁

**Comment by Mr-AlbertZhang** [comment]
> 这是因为你复制粘贴后的预设具有不同的UUID，如果你没有改JS代码中的UUID，那么JS的代码只会更新原来那个预设的devNAME。
> 
> 你需要进行的操作是：选择你复制后的预设，右键点击-选择复制UUID，然后在JS代码中把原来的那一串UUID替换掉即可～
> 
> 其实BTT菜单里面有“移动trigger到”这个功能，这样就可以避免这个问题了😁

太感谢了，我确实也发现了这样的情况，但是不知道问题是为什么，原来是UUID，我确实发现JS中有一段数字，不知道干嘛了，我最后发现了移动这个功能，确实解决了问题，感谢感谢！

**Comment by noonchen** [comment]
> 你已经非常棒了👍，你的顾虑我想了下，也非常有道理，有些人确实需要同时连接两个蓝牙设备，Macos默认音频只能从一个通道输出吧（能不能多输出？我还没求证），大家可以继续交流，如果你有临时的版本 我可以帮你测试，zhangdong#zua.edu.cn（#换成@）再次感谢你的交流

Hi, 花了几天学了objective-c然后写了个命令行工具来保证切换蓝牙设备会同时也换音频设备，我都打包到一起[commit](https://github.com/noonchen/BTT_AppleWirelessHeadphone/blob/master/AppleHeadphone_0523.bttpresetzip)了，还请帮忙测试一下。

切换逻辑有所改变：
假设两个蓝牙耳机A和B同时与mac连接了。
1. 如果当前音频设备是A，激活了A的tigger会正常的将A断开，B也同理（这和当前的功能一致）；
2. 如果当前音频设备是A，激活了B的trigger，此时会将音频设备切换至B，而不是断开B；

其他的逻辑保持不变，你亲自实验就明白了😁

**Comment by Mr-AlbertZhang** [comment]
好的，这边我就下载测试下 我使用过后给您反馈  感谢感谢

**Comment by Mr-AlbertZhang** [comment]
首先感谢这位少主这么辛苦的，这么快就更新了配置，很是感动，以下是我在三种情况下测试的具体情况，如果嫌麻烦请直接看结论
---------------------------
测试一
假设两个耳机蓝牙都在连接
1.这时可以看到在A设备在Bar面板绿色；
蓝牙：A(连) B(连)
音频：A(连) B(断)
结论：正确
2.轻点Bar激活tigger1#，此时Bar显示A设备灰色；
蓝牙：A(断) B(连)
音频：A(断) B(连) 
结论：不正确，应该由扬声器
3.长按Bar激活tigger2#，此时Bar上显示B设备为灰色；
蓝牙：A(断) B(断)
音频：A(断) B(断) 转为扬声器
结论：正确
4.再次长按Bar激活tigger2#，此时Bar上显示B设备为绿色；
蓝牙：A(断) B(连)
音频：A(断) B(连) 
结论：正确
5.轻点轻点Bar，激活tigger1#，此时Bar上显示A设备为绿色；
蓝牙：A(连) B(连)
音频：A(连) B(断) 
结论：正确
该模式，测试结束！
------------------------------------------------------------------
测试二
假设两个耳机蓝牙都在连接
1.这时可以看到在A设备在Bar面板绿色；
蓝牙：A(连) B(连)
音频：A(连) B(断)
结论：正确
2.长按Bar激活tigger2#，此时B设备在面板绿色；
蓝牙：A(连) B(连)
音频：A(断) B(连)
结论：正确
3.再次长按Bar再次激活tigger2#，此时Bar上显示B设备为灰色；
蓝牙：A(连) B(断)
音频：A(断) B(断) 转为扬声器
结论：正确
4.轻点Bar，激活tigger1#，此时Bar上显示A设备为绿色；
蓝牙：A(连) B(断)
音频：A(连) B(断) 
结论：正确
5.再次轻点轻点Bar，激活tigger1#，此时Bar上显示A设备为灰色；
蓝牙：A(断) B(断)
音频：A(断) B(断) 转为扬声器 
结论：正确
该模式，测试结束！
-----------------------------------------------------------------------
测试三
假设两个耳机蓝牙都在连接
1.这时可以看到在A设备在Bar面板绿色；
蓝牙：A(连) B(连)
音频：A(连) B(断)
结论：正确
2.长按Bar激活tigger2#，此时Bar上显示B设备为绿色；
蓝牙：A(连) B(连)
音频：A(断) B(连)
结论：正确
3.长按Bar激活tigger2#，此时Bar上显示B设备为灰色；
蓝牙：A(连) B(断)
音频：A(断) B(断) 转为扬声器
结论：正确
4.轻按Bar激活tigger1#，此时Bar上显示A设备为绿；
蓝牙：A(连) B(断)
音频：A(连) B(断)
结论：正确
5.长按Bar激活tigger2#，此时Bar上显示B设备为绿；
蓝牙：A(连) B(连)
音频：A(断) B(连)
结论：正确
该模式，测试结束！
----------------------------------------------------------------------------
结论：测试一，第二项逻辑上有问题：Bar已经显示A设备灰色，应该由默认输出扬声器输出，第三项-第四项虽然在操作上有些问题，但是Bar显示（绿色）和输出照应，不是问题。
测试中发现：虽然在Bar上操作后蓝牙确实显示断开，见图，蓝牙中也看到断开了，但是音频输出里面还能看到这个设备（没有关耳机的情况），点击音频这个设备能够快速连接上蓝牙，能不能提供一种切换思路？
十分的感谢能提供这么好的预设和这么热情的回答！

![2](https://user-images.githubusercontent.com/59662570/82736398-24500f00-9d5c-11ea-962b-baa20eef4466.jpg)
![1](https://user-images.githubusercontent.com/59662570/82736403-287c2c80-9d5c-11ea-95e7-d9b61e25b0d9.jpg)
![iShot2020-05-24上午01 08 39](https://user-images.githubusercontent.com/59662570/82736423-48135500-9d5c-11ea-9f70-c5f3c43d871b.jpg)
![iShot2020-05-24上午01 08 54](https://user-images.githubusercontent.com/59662570/82736433-57929e00-9d5c-11ea-813b-5d152adc3cb0.jpg)

**Comment by noonchen** [comment]
感谢你这么晚还帮我测试😂，针对你遇到的问题，解答如下：
1. 测试一#2中断开A后音频切换至了B而没有切换成扬声器，这其实是macOS的连接逻辑，这不是我控制的，当有音频设备连接至mac后，macOS会优先将其设为默认音频输入输出，这就是为什么断开A会自动连接B，我个人比较认同此逻辑会符合大多数的生活场景。
此外，断开设备自动连接扬声器在程序中并不好实现，因为CoreAudio中的API并没有直接获得mac内置音频设备ID的方法，只能获取所有设备并逐个判断是否为内置设备，再判断是否为输入/输出设备，最后还要再设置为默认音频...

2. 测试一#3#4遇到的操作问题具体指的是哪些呢？

3. 蓝牙断开后还能在音频设备中看到，这一点也是macOS的锅，即使耳机关机了或者AirPods放到盒子后，在一段时间内还是会在音频中出现，我猜应该是音频设备刷新速度没有那么快吧。关于点击设备可以快速连接蓝牙，我不知道苹果是怎么做的🤔，我是用CoreAudio和IOBluetooth这两个framework实现以上的功能，这也是多数开发者操作音频和蓝牙使用的模块，暂时应该没什么可以改的了😂...

**Comment by Mr-AlbertZhang** [comment]
你好，非常感谢提供的预设，感觉这个已经是非常完美了
1.针对没有切换成扬声器（默认），估计我有点吹毛求疵了，确实符合大多数场景，但是有个问题我们也可讨论下，在测试二中2-3测试三2-3中同样是这样情况蓝牙还连接着A，为什么从扬声器输出（按照测试一推理不应该从A设备输出吗？）？
2.测试一#3#4遇到的操作问题具体指的是哪些呢？：这个更可能是我认为的情况，在程序测试和功能均能符合（Bar显示和实际输出状况），以下内容是我瞎想的：比如我按下测试一2#后（假定输出是扬声器其实是B设备），此时界面为A设备灰色，此时我长按激活tigger2#，按照想的是此时应该连接B设备，但是实际是因为这时候是B设备蓝牙连接，激活tigger2#会断开B设备的蓝牙。我觉得只要是Bar显示和实际输出照应这就没问题。
3.我在你的原始版本上进行以下更改能够实现基本的切换，见下图。不过我觉得js更加稳定，而且封装的更加好，切换毫无压力👍
最后，感谢你为我新增了功能，还有这么细致的解答。祝福学习进步！欢迎常交流！

![iShot2020-05-24下午07 11 30](https://user-images.githubusercontent.com/59662570/82752733-b73b8880-9df2-11ea-8497-d9c3226610ee.jpg)
![iShot2020-05-24下午07 11 42](https://user-images.githubusercontent.com/59662570/82752735-b99de280-9df2-11ea-9f07-b7c6ce1cd145.jpg)

**Comment by noonchen** [comment]
1. 你发现了盲点，那我之前的想法就全错了，我现在也不知道macOS的逻辑是啥了😂。。
2. 你说的这个非常合理，当macOS自动将音频输出至B，但是我的preset还是显示的A的状态，理想的情况是preset自动随着macOS转成设备B的信息，但难度好大 = =，一是macOS切换设备好像没什么规律；二是命令行工具和preset是独立开的，没法传给preset信息（我想让功能尽可能分离，避免耦合导致问题变复杂）。

这么看的话，还不如断开设备之后直接切换成内置设备来的方便，防止macOS随意切换音频设备导致preset的显示问题。。。

**Comment by noonchen** [comment]
对了，我想请你帮个忙，能否帮我截下BeatsX激活时的touch bar图像？我想放到ReadMe上供其他人参考下BeatsX的显示效果😁

如果不嫌麻烦的话，还请在BeatsX连接以及断开的时候按住`shift+command+6`截个图，感谢🙏

**Comment by Mr-AlbertZhang** [comment]
你已经非常棒了，功能也很完善，我已经把你最新的这个版本融合到我以前的预设中了，再次感谢！没有问题，我已经截图放下面，你可以下载！

**Comment by Mr-AlbertZhang** [comment]
你已经非常棒了，功能也很完善，我已经把你最新的这个版本融合到我以前的预设中了，再次感谢！没有问题，我已经截图放下面，你可以下载！
<img width="1085" alt="触控栏快照2020-05-25 上午12 28 41" src="https://user-images.githubusercontent.com/59662570/82759385-b240fe00-9e1f-11ea-8a6b-8a9afd9e1d63.png">
<img width="1085" alt="触控栏快照2020-05-25 上午12 29 59" src="https://user-images.githubusercontent.com/59662570/82759388-b40ac180-9e1f-11ea-944d-6ecc0416e3e3.png">

**Comment by Mr-AlbertZhang** [comment]
你好，又遇到一个问题，我把你最新的V1.1融合进入我的原有预设中，我是使用了移动trigger，提示下图，移动到我的配置中，但是无法实现切换，想问下问题出现在哪？谢谢
![iShot2020-06-03下午06 56 01](https://user-images.githubusercontent.com/59662570/83628987-eeb4ec80-a5cb-11ea-9c0b-007b9fbc1945.jpg)
